user_feature_file_path: /data2/zhy/Movie_Recsys/data/user_feature.dat
item_feature_file_path: /data2/zhy/Movie_Recsys/data/item_feature.dat
train_data_path: /data2/zhy/Movie_Recsys/data/train_ratings.dat
test_data_path: /data2/zhy/Movie_Recsys/data/test_ratings.dat

user_feature_config:
  userid:  # 特征名
    FeatureKind: kind # 特征类型，kind代表是一个单独的kind特征，还有kindarray，代表是kind特征的列表
    AggreateMethod: none
    MaxIndex: 10000 # 这个特征有多少个取值，比如userid特征就是用户的数量，因为每个用户都有这么一个userid
    Dim: 16 # 特征最后的嵌入维度
    Depend: 0 # 依赖于user feature的第几列特征，user特征默认从user对应的特征文件中获取值
    type: int


item_feature_config:
  itemid:
    FeatureKind: kind # 特征类型，kind代表是一个单独的kind特征，还有kindarray，代表是kind特征的列表
    AggreateMethod: none
    KindNum: 100 # 这个特征有多少个取值，比如userid特征就是用户的数量，因为每个用户都有这么一个userid
    Dim: 16 # 特征最后的嵌入维度
    Depend: 0 # 依赖于user feature的第几列特征，user特征默认从user对应的特征文件中获取值
    type: int
    MaxIndex: 10000